// Code generated by ent, DO NOT EDIT.

package eventinvite

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/abc3354/CODEV-back/ent/predicate"
	"github.com/google/uuid"
)

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v uuid.UUID) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldEQ(FieldProfileID, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v int) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldEQ(FieldEventID, v))
}

// Since applies equality check predicate on the "since" field. It's identical to SinceEQ.
func Since(v time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldEQ(FieldSince, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v uuid.UUID) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v uuid.UUID) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...uuid.UUID) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...uuid.UUID) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldNotIn(FieldProfileID, vs...))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v int) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v int) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...int) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...int) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldNotIn(FieldEventID, vs...))
}

// SinceEQ applies the EQ predicate on the "since" field.
func SinceEQ(v time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldEQ(FieldSince, v))
}

// SinceNEQ applies the NEQ predicate on the "since" field.
func SinceNEQ(v time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldNEQ(FieldSince, v))
}

// SinceIn applies the In predicate on the "since" field.
func SinceIn(vs ...time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldIn(FieldSince, vs...))
}

// SinceNotIn applies the NotIn predicate on the "since" field.
func SinceNotIn(vs ...time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldNotIn(FieldSince, vs...))
}

// SinceGT applies the GT predicate on the "since" field.
func SinceGT(v time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldGT(FieldSince, v))
}

// SinceGTE applies the GTE predicate on the "since" field.
func SinceGTE(v time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldGTE(FieldSince, v))
}

// SinceLT applies the LT predicate on the "since" field.
func SinceLT(v time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldLT(FieldSince, v))
}

// SinceLTE applies the LTE predicate on the "since" field.
func SinceLTE(v time.Time) predicate.EventInvite {
	return predicate.EventInvite(sql.FieldLTE(FieldSince, v))
}

// HasProfile applies the HasEdge predicate on the "profile" edge.
func HasProfile() predicate.EventInvite {
	return predicate.EventInvite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ProfileColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ProfileTable, ProfileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProfileWith applies the HasEdge predicate on the "profile" edge with a given conditions (other predicates).
func HasProfileWith(preds ...predicate.Profile) predicate.EventInvite {
	return predicate.EventInvite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ProfileColumn),
			sqlgraph.To(ProfileInverseTable, ProfileFieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProfileTable, ProfileColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.EventInvite {
	return predicate.EventInvite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, EventColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.EventInvite {
	return predicate.EventInvite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, EventColumn),
			sqlgraph.To(EventInverseTable, EventFieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, EventTable, EventColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EventInvite) predicate.EventInvite {
	return predicate.EventInvite(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EventInvite) predicate.EventInvite {
	return predicate.EventInvite(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EventInvite) predicate.EventInvite {
	return predicate.EventInvite(func(s *sql.Selector) {
		p(s.Not())
	})
}
