// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/abc3354/CODEV-back/ent/eventinvite"
	"github.com/abc3354/CODEV-back/ent/predicate"
)

// EventInviteDelete is the builder for deleting a EventInvite entity.
type EventInviteDelete struct {
	config
	hooks    []Hook
	mutation *EventInviteMutation
}

// Where appends a list predicates to the EventInviteDelete builder.
func (eid *EventInviteDelete) Where(ps ...predicate.EventInvite) *EventInviteDelete {
	eid.mutation.Where(ps...)
	return eid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (eid *EventInviteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, EventInviteMutation](ctx, eid.sqlExec, eid.mutation, eid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (eid *EventInviteDelete) ExecX(ctx context.Context) int {
	n, err := eid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (eid *EventInviteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: eventinvite.Table,
		},
	}
	if ps := eid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, eid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	eid.mutation.done = true
	return affected, err
}

// EventInviteDeleteOne is the builder for deleting a single EventInvite entity.
type EventInviteDeleteOne struct {
	eid *EventInviteDelete
}

// Exec executes the deletion query.
func (eido *EventInviteDeleteOne) Exec(ctx context.Context) error {
	n, err := eido.eid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventinvite.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eido *EventInviteDeleteOne) ExecX(ctx context.Context) {
	eido.eid.ExecX(ctx)
}
