// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abc3354/CODEV-back/ent/predicate"
	"github.com/abc3354/CODEV-back/ent/salledisponible"
)

// SalleDisponibleDelete is the builder for deleting a SalleDisponible entity.
type SalleDisponibleDelete struct {
	config
	hooks    []Hook
	mutation *SalleDisponibleMutation
}

// Where appends a list predicates to the SalleDisponibleDelete builder.
func (sdd *SalleDisponibleDelete) Where(ps ...predicate.SalleDisponible) *SalleDisponibleDelete {
	sdd.mutation.Where(ps...)
	return sdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sdd *SalleDisponibleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, SalleDisponibleMutation](ctx, sdd.sqlExec, sdd.mutation, sdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sdd *SalleDisponibleDelete) ExecX(ctx context.Context) int {
	n, err := sdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sdd *SalleDisponibleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: salledisponible.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: salledisponible.FieldID,
			},
		},
	}
	if ps := sdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sdd.mutation.done = true
	return affected, err
}

// SalleDisponibleDeleteOne is the builder for deleting a single SalleDisponible entity.
type SalleDisponibleDeleteOne struct {
	sdd *SalleDisponibleDelete
}

// Exec executes the deletion query.
func (sddo *SalleDisponibleDeleteOne) Exec(ctx context.Context) error {
	n, err := sddo.sdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{salledisponible.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sddo *SalleDisponibleDeleteOne) ExecX(ctx context.Context) {
	sddo.sdd.ExecX(ctx)
}
