// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abc3354/CODEV-back/ent/predicate"
	"github.com/abc3354/CODEV-back/ent/salle"
)

// SalleDelete is the builder for deleting a Salle entity.
type SalleDelete struct {
	config
	hooks    []Hook
	mutation *SalleMutation
}

// Where appends a list predicates to the SalleDelete builder.
func (sd *SalleDelete) Where(ps ...predicate.Salle) *SalleDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SalleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, SalleMutation](ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SalleDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SalleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: salle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: salle.FieldID,
			},
		},
	}
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// SalleDeleteOne is the builder for deleting a single Salle entity.
type SalleDeleteOne struct {
	sd *SalleDelete
}

// Exec executes the deletion query.
func (sdo *SalleDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{salle.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SalleDeleteOne) ExecX(ctx context.Context) {
	sdo.sd.ExecX(ctx)
}
